/**
 * Deprecated: sitemap + robots are generated by Next.js App Router:
 *   - src/app/sitemap.ts
 *   - src/app/robots.ts
 *
 * Do not run `next-sitemap` postbuild — it overwrote public/ with localhost URLs
 * and indexed private CRM/admin routes.
 *
 * @type {import('next-sitemap').IConfig}
 */
module.exports = {
  siteUrl: process.env.NEXT_PUBLIC_SITE_URL || 'https://www.tempesttreks.in',
  generateRobotsTxt: false,
  generateIndexSitemap: false,
};
